import { IUtilizadores } from '../../shared/i-utilizadores';

const DataDummyObjeto: IUtilizadores = {
  id: 100,
  email: 'tony@gmail.com',
  idade: 42,
  ativo: true,
  dataRegistro: new Date(),
  departamento: 'comercial de vendas',
  salario: 1000,
};
//export const DataDummy: IUtilizador = [{...DataDummy2}];
export const DataDummy: IUtilizadores[] = [
  DataDummyObjeto,
  {
    id: 101,
    email: 'ana@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date('2023-01-05'),
    departamento: 'dep informatico',
    salario: 1000,
  },
  {
    id: 102,
    email: 'leo@gmail.com',
    idade: 20,
    ativo: true,
    dataRegistro: new Date('2025-01-01'),
    departamento: 'dep informatico',
    salario: 1000,
  },
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    departamento: 'comercial de vendas',
    salario: 1000,
  },
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    departamento: 'comercial de vendas',
    salario: 1000,
  },
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    departamento: 'comercial de vendas',
    salario: 1000,
  },
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    departamento: 'comercial de vendas',
    salario: 1000,
  },
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    departamento: 'comercial de vendas',
    salario: 1000,
  },
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    departamento: 'comercial de vendas',
    salario: 1000,
  },
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    departamento: 'comercial de vendas',
    salario: 1000,
  },
];
